apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: e13q/django-site:9a146d1022889d81b954898699b19996ea50362e
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: django-secrets
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /root/.postgresql
          name: pg-root-cert
          readOnly: true
      volumes:
      - name: pg-root-cert
        secret:
          secretName: pg-root-cert



